--- #YAML:1.0
name:               Brackup
version:            1.10
abstract:           Flexible backup tool.  Slices, dices, encrypts, and sprays across the net.
author:
    - Brad Fitzpatrick <brad@danga.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBD::SQLite:         0
    DBI:                 0
    Digest::SHA1:        0
    ExtUtils::Manifest:  1.52
    File::Temp:          0.17
    IO::InnerFile:       0
    String::Escape:      0
    Test::More:          0.88
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
